import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from textwrap import wrap
from io import BytesIO
from datetime import datetime

from config import PALETTE
from ui import label_color
from data.processor import best_k_index


# ── Internal helpers ──────────────────────────────────────────────────────────

def _pdf_footer(fig, generated_at):
    fig.text(0.06, 0.035, 'Generated by Inventory Analytics System', fontsize=8.5, color='#64748B')
    fig.text(0.94, 0.035, generated_at, fontsize=8.5, color='#64748B', ha='right')


def _result_metrics(results):
    if not results:
        return {'K': '-', 'Silhouette': np.nan, 'DBI': np.nan}
    best = results[best_k_index(results)]
    return {'K': best['K'], 'Silhouette': best['Silhouette'], 'DBI': best['DBI']}


def _pdf_page(pdf, title, lines, table_df=None):
    generated_at = datetime.now().strftime('%d %B %Y %H:%M')
    fig = plt.figure(figsize=(11.69, 8.27))
    ax = fig.add_axes([0, 0, 1, 1])
    ax.axis('off')
    ax.text(0.06, 0.94, title, fontsize=18, weight='bold', color=PALETTE['bg_dark'])

    y = 0.88
    for line in lines:
        for chunk in wrap(str(line), 105):
            ax.text(0.06, y, chunk, fontsize=10.5, color=PALETTE['text_dark'])
            y -= 0.034
        y -= 0.006

    if table_df is not None and not table_df.empty:
        table_ax = fig.add_axes([0.05, 0.08, 0.90, max(0.22, y - 0.10)])
        table_ax.axis('off')
        show_df = table_df.head(16).copy()
        cell_text = show_df.astype(str).values.tolist()
        col_width = 1 / max(len(show_df.columns), 1)
        table = table_ax.table(
            cellText=cell_text,
            colLabels=show_df.columns.tolist(),
            cellLoc='left', colLoc='left',
            colWidths=[col_width] * len(show_df.columns),
            loc='upper left',
        )
        table.auto_set_font_size(False)
        table.set_fontsize(8)
        table.scale(1, 1.35)
        for (row, col), cell in table.get_celld().items():
            cell.set_edgecolor('#CBD5E1')
            if row == 0:
                cell.set_facecolor('#E8F1FB')
                cell.set_text_props(weight='bold', color=PALETTE['bg_dark'])
            else:
                cell.set_facecolor('white')
                cell.set_text_props(color=PALETTE['text_dark'])

    _pdf_footer(fig, generated_at)
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)


def _pdf_bar_page(pdf, title, series, xlabel):
    generated_at = datetime.now().strftime('%d %B %Y %H:%M')
    series = series.dropna().sort_values(ascending=True).tail(12)
    if series.empty:
        return

    fig, ax = plt.subplots(figsize=(11.69, 8.27))
    fig.patch.set_facecolor('white')
    ax.barh(series.index.astype(str), series.values, color=PALETTE['secondary'], edgecolor=PALETTE['bg_dark'])
    ax.set_title(title, fontsize=17, fontweight='bold', color=PALETTE['bg_dark'], pad=18)
    ax.set_xlabel(xlabel, fontsize=10, color=PALETTE['text_dark'])
    ax.tick_params(axis='both', labelsize=9, colors=PALETTE['text_dark'])
    ax.grid(axis='x', color='#E2E8F0', linewidth=0.8)
    ax.set_axisbelow(True)
    for spine in ax.spines.values():
        spine.set_color('#CBD5E1')
    for i, value in enumerate(series.values):
        ax.text(value, i, f' {value:,.0f}', va='center', fontsize=8.5, color=PALETTE['text_dark'])
    _pdf_footer(fig, generated_at)
    fig.tight_layout(rect=[0.03, 0.06, 0.98, 0.96])
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)


def _pdf_cover(pdf, generated_at):
    fig = plt.figure(figsize=(11.69, 8.27), facecolor='#F5F7FA')
    ax = fig.add_axes([0, 0, 1, 1])
    ax.axis('off')
    ax.add_patch(plt.Rectangle((0.06, 0.16), 0.88, 0.68, facecolor='white', edgecolor='#CBD5E1', linewidth=1.2))
    ax.add_patch(plt.Rectangle((0.06, 0.78), 0.88, 0.06, facecolor=PALETTE['bg_dark'], edgecolor=PALETTE['bg_dark']))
    ax.text(0.10, 0.72, 'Laporan Analisis Inventory ATK\nBerbasis K-Means Clustering',
            fontsize=25, weight='bold', color=PALETTE['bg_dark'], va='top')
    ax.text(0.10, 0.53, 'Inventory Analytics System', fontsize=15, color=PALETTE['accent'], weight='bold')
    ax.text(0.10, 0.48, 'Dashboard segmentasi konsumsi divisi, pergerakan produk ATK, dan prioritas divisi-item.',
            fontsize=11, color='#475569')
    ax.text(0.10, 0.38, f'Tanggal generate laporan: {generated_at}', fontsize=11, color=PALETTE['text_dark'])
    ax.text(0.10, 0.28, 'Bank Raya Indonesia', fontsize=13, color=PALETTE['bg_dark'], weight='bold')
    _pdf_footer(fig, generated_at)
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)


def _pdf_exec_summary(pdf, lines, generated_at):
    fig = plt.figure(figsize=(11.69, 8.27), facecolor='white')
    ax = fig.add_axes([0, 0, 1, 1])
    ax.axis('off')
    ax.text(0.06, 0.92, 'Executive Summary', fontsize=21, weight='bold', color=PALETTE['bg_dark'])
    y = 0.82
    for i, line in enumerate(lines, 1):
        ax.add_patch(plt.Rectangle((0.06, y - 0.045), 0.88, 0.07, facecolor='#F8FAFC', edgecolor='#E2E8F0'))
        ax.text(0.085, y, f'{i}', fontsize=12, weight='bold', color='white',
                bbox=dict(boxstyle='circle,pad=0.35', facecolor=PALETTE['accent'], edgecolor=PALETTE['accent']))
        ax.text(0.13, y + 0.004, line, fontsize=11.2, color=PALETTE['text_dark'], va='center')
        y -= 0.10
    _pdf_footer(fig, generated_at)
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)


def _pdf_eval_page(pdf, eval_rows, generated_at):
    fig = plt.figure(figsize=(11.69, 8.27), facecolor='white')
    ax = fig.add_axes([0, 0, 1, 1])
    ax.axis('off')
    ax.text(0.06, 0.92, 'Evaluasi Cluster', fontsize=21, weight='bold', color=PALETTE['bg_dark'])
    table_df = pd.DataFrame(eval_rows)
    table_ax = fig.add_axes([0.08, 0.48, 0.84, 0.30])
    table_ax.axis('off')
    table = table_ax.table(
        cellText=table_df.astype(str).values.tolist(),
        colLabels=table_df.columns.tolist(),
        cellLoc='center', colLoc='center', loc='center',
    )
    table.auto_set_font_size(False)
    table.set_fontsize(10)
    table.scale(1, 1.8)
    for (row, col), cell in table.get_celld().items():
        cell.set_edgecolor('#CBD5E1')
        if row == 0:
            cell.set_facecolor('#E8F1FB')
            cell.set_text_props(weight='bold', color=PALETTE['bg_dark'])
        else:
            cell.set_facecolor('white')
            cell.set_text_props(color=PALETTE['text_dark'])
    ax.text(0.08, 0.36, 'Interpretasi singkat:', fontsize=12, weight='bold', color=PALETTE['bg_dark'])
    ax.text(0.08, 0.31, 'Silhouette semakin tinggi semakin baik. DBI semakin rendah semakin baik.',
            fontsize=10.5, color='#475569')
    _pdf_footer(fig, generated_at)
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)


def _pdf_scatter_page(pdf, title, data, x, y, label_col, generated_at):
    if data is None or data.empty:
        return
    fig, ax = plt.subplots(figsize=(11.69, 8.27), facecolor='white')
    for i, lbl in enumerate(data[label_col].dropna().unique()):
        sub = data[data[label_col] == lbl]
        color = label_color(lbl, i)
        ax.scatter(sub[x], sub[y], s=58, alpha=0.86, color=color, edgecolor='white', linewidth=0.8, label=lbl)
        centroid = sub[[x, y]].mean()
        ax.scatter(centroid[x], centroid[y], s=220, marker='X', color='white', edgecolor=color, linewidth=2.6)
        ax.text(centroid[x], centroid[y], ' Centroid', fontsize=8.5, color=color, weight='bold')
    ax.set_title(title, fontsize=18, fontweight='bold', color=PALETTE['bg_dark'], pad=18)
    ax.set_xlabel(x, fontsize=10.5, color=PALETTE['text_dark'])
    ax.set_ylabel(y, fontsize=10.5, color=PALETTE['text_dark'])
    ax.grid(True, color='#E2E8F0', linewidth=0.8)
    ax.legend(loc='best', frameon=True, facecolor='white', edgecolor='#CBD5E1')
    ax.tick_params(colors=PALETTE['text_dark'])
    for spine in ax.spines.values():
        spine.set_color('#CBD5E1')
    fig.text(0.06, 0.035, 'Generated by Inventory Analytics System', fontsize=8.5, color='#64748B')
    fig.text(0.94, 0.035, generated_at, fontsize=8.5, color='#64748B', ha='right')
    fig.tight_layout(rect=[0.04, 0.06, 0.96, 0.94])
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)


def _pdf_heatmap_page(pdf, m3, generated_at):
    if m3 is None or m3.empty:
        return
    top_d = m3.groupby('Divisi')['Skor_Ketergantungan'].max().nlargest(12).index
    top_i = m3.groupby('Jenis_ATK')['Skor_Ketergantungan'].max().nlargest(10).index
    pivot = m3[m3['Divisi'].isin(top_d) & m3['Jenis_ATK'].isin(top_i)].pivot_table(
        index='Divisi', columns='Jenis_ATK', values='Skor_Ketergantungan', fill_value=0
    )
    fig, ax = plt.subplots(figsize=(11.69, 8.27), facecolor='white')
    im = ax.imshow(pivot.values, cmap='RdYlBu_r', aspect='auto')
    ax.set_title('Model 3 - Heatmap Prioritas Divisi-Item', fontsize=18, fontweight='bold',
                 color=PALETTE['bg_dark'], pad=18)
    ax.set_xticks(range(len(pivot.columns)))
    ax.set_xticklabels(pivot.columns, rotation=35, ha='right', fontsize=8.5, color=PALETTE['text_dark'])
    ax.set_yticks(range(len(pivot.index)))
    ax.set_yticklabels(pivot.index, fontsize=8.5, color=PALETTE['text_dark'])
    cbar = fig.colorbar(im, ax=ax, fraction=0.026, pad=0.02)
    cbar.ax.tick_params(labelsize=8, colors=PALETTE['text_dark'])
    cbar.set_label('Skor Ketergantungan', color=PALETTE['text_dark'])
    fig.text(0.06, 0.035, 'Generated by Inventory Analytics System', fontsize=8.5, color='#64748B')
    fig.text(0.94, 0.035, generated_at, fontsize=8.5, color='#64748B', ha='right')
    fig.tight_layout(rect=[0.04, 0.06, 0.96, 0.94])
    pdf.savefig(fig, bbox_inches='tight')
    plt.close(fig)


def _model_insights(m1, m2, m3):
    lines = []
    if m1 is not None and not m1.empty:
        dominant = m1['Label'].value_counts().idxmax()
        pct = m1['Label'].value_counts(normalize=True).max() * 100
        lines.append(f'Cluster konsumsi {dominant.lower()} mendominasi sebanyak {pct:.0f}% dari total divisi.')
    if m2 is not None and not m2.empty:
        fast = m2[m2['Label'].eq('Fast Moving')]
        source = fast if not fast.empty else m2
        top = source.sort_values('Frekuensi', ascending=False).iloc[0]
        lines.append(f'{top["Jenis_ATK"]} merupakan produk dengan frekuensi tertinggi pada kelompok {top["Label"]}.')
    if m3 is not None and not m3.empty:
        high_count = int((m3['Label'] == 'Prioritas Tinggi').sum())
        lines.append(f'Terdapat {high_count:,} pasangan divisi-item prioritas tinggi.')
    return lines


# ── Public export function ────────────────────────────────────────────────────

def to_pdf_report(df, m1, m2, m3, m1_res=None, m2_res=None, m3_res=None) -> bytes:
    generated_at = datetime.now().strftime('%d %B %Y %H:%M')
    buf = BytesIO()
    eval_rows = []
    for name, results in [
        ('Model 1 - Konsumsi Divisi',         m1_res),
        ('Model 2 - Pergerakan Produk ATK',    m2_res),
        ('Model 3 - Prioritas Divisi-Item',    m3_res),
    ]:
        metrics = _result_metrics(results)
        eval_rows.append({
            'Model': name,
            'K Optimal': metrics['K'],
            'Silhouette Score': '-' if pd.isna(metrics['Silhouette']) else f'{metrics["Silhouette"]:.4f}',
            'DBI': '-' if pd.isna(metrics['DBI']) else f'{metrics["DBI"]:.4f}',
        })

    with PdfPages(buf) as pdf:
        _pdf_cover(pdf, generated_at)

        summary_lines = [
            f'Total transaksi yang dianalisis adalah {len(df):,} dengan total permintaan {df["Jumlah"].sum():,.0f} unit.',
            f'Dataset mencakup {df["Divisi"].nunique():,} divisi dan {df["Jenis_ATK"].nunique():,} jenis ATK.',
        ]
        summary_lines.extend(_model_insights(m1, m2, m3))
        _pdf_exec_summary(pdf, summary_lines, generated_at)

        overview_lines = [
            f'Total transaksi: {len(df):,}',
            f'Total divisi: {df["Divisi"].nunique():,}',
            f'Total jenis ATK: {df["Jenis_ATK"].nunique():,}',
            f'Total permintaan: {df["Jumlah"].sum():,.0f} unit',
            f'Rata-rata per transaksi: {df["Jumlah"].mean():.2f} unit',
        ]
        _pdf_page(pdf, 'Overview Dashboard Inventory ATK', overview_lines)
        _pdf_bar_page(pdf, 'Top Divisi Berdasarkan Permintaan',
                      df.groupby('Divisi')['Jumlah'].sum(), 'Total Permintaan (Unit)')
        _pdf_bar_page(pdf, 'Top Item ATK Berdasarkan Frekuensi',
                      df.groupby('Jenis_ATK').size(), 'Frekuensi Transaksi')

        if m1 is not None:
            table = m1.groupby(['Cluster', 'Label']).agg(
                Jumlah_Divisi=('Divisi', 'count'),
                Rata_Volume=('Volume', 'mean'),
                Rata_Frekuensi=('Frekuensi', 'mean'),
            ).reset_index().round(2)
            dominant = m1['Label'].value_counts().idxmax()
            pct = m1['Label'].value_counts(normalize=True).max() * 100
            lines = [
                f'Divisi dianalisis: {len(m1):,}',
                f'Total volume: {m1["Volume"].sum():,.0f} unit',
                f'Rata-rata frekuensi: {m1["Frekuensi"].mean():.1f} transaksi',
                f'Insight: Cluster konsumsi {dominant.lower()} mendominasi sebanyak {pct:.0f}% dari total divisi.',
            ]
            _pdf_page(pdf, 'Model 1 - Segmentasi Konsumsi Divisi', lines, table)
            _pdf_scatter_page(pdf, 'Model 1 Scatter: Volume vs Frekuensi',
                              m1, 'Volume', 'Frekuensi', 'Label', generated_at)

        if m2 is not None:
            table = m2.groupby(['Cluster', 'Label']).agg(
                Jumlah_Produk=('Jenis_ATK', 'count'),
                Rata_Frekuensi=('Frekuensi', 'mean'),
                Rata_Total_Jumlah=('Total_Jumlah', 'mean'),
                Rata_Jumlah_Divisi=('Jumlah_Divisi', 'mean'),
            ).reset_index().round(2)
            fast = m2[m2['Label'].eq('Fast Moving')]
            source = fast if not fast.empty else m2
            top = source.sort_values('Frekuensi', ascending=False).iloc[0]
            lines = [
                f'Produk dianalisis: {len(m2):,}',
                f'Total permintaan: {m2["Total_Jumlah"].sum():,.0f} unit',
                f'Rata-rata frekuensi: {m2["Frekuensi"].mean():.1f} transaksi',
                f'Insight: {top["Jenis_ATK"]} merupakan produk {top["Label"]} dengan frekuensi tertinggi.',
            ]
            _pdf_page(pdf, 'Model 2 - Segmentasi Pergerakan Produk ATK', lines, table)
            _pdf_scatter_page(pdf, 'Model 2 Scatter: Frekuensi vs Total Unit',
                              m2, 'Frekuensi', 'Total_Jumlah', 'Label', generated_at)

        if m3 is not None:
            table = m3.groupby(['Cluster', 'Label']).agg(
                Jumlah_Pasangan=('Divisi', 'count'),
                Rata_Skor=('Skor_Ketergantungan', 'mean'),
                Rata_Frekuensi=('Frekuensi', 'mean'),
                Rata_Total_Jumlah=('Total_Jumlah', 'mean'),
            ).reset_index().round(4)
            high_count = int((m3['Label'] == 'Prioritas Tinggi').sum())
            lines = [
                f'Pasangan divisi-item: {len(m3):,}',
                f'Total volume: {m3["Total_Jumlah"].sum():,.0f} unit',
                f'Rata-rata skor ketergantungan: {m3["Skor_Ketergantungan"].mean():.3f}',
                f'Insight: Terdapat {high_count:,} pasangan divisi-item prioritas tinggi.',
            ]
            _pdf_page(pdf, 'Model 3 - Segmentasi Prioritas Divisi-Item', lines, table)
            _pdf_heatmap_page(pdf, m3, generated_at)
            prioritas = m3[m3['Label'] == 'Prioritas Tinggi']
            if prioritas.empty:
                prioritas = m3
            _pdf_bar_page(pdf, 'ATK Prioritas Tinggi Berdasarkan Volume',
                          prioritas.groupby('Jenis_ATK')['Total_Jumlah'].sum(), 'Total Permintaan (Unit)')

        _pdf_eval_page(pdf, eval_rows, generated_at)

    return buf.getvalue()
